export const ActionTypes = {
    SEARCH_IMAGES: 'SEARCH_IMAGES',
    SELECTED_IMAGE: 'SELECTED_IMAGE',
    DELETE_IMAGE: 'DELETE_IMAGE',
    LOG_IN: 'LOG_IN',
    SIGN_OUT: 'SIGN_OUT',
    EMPTY_FAVOURITES: 'EMPTY_FAVOURITES',
    CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
};
